spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: iflow-engine
          uri: lb://iflow-engine  # Eureka'da kayıtlı olan servis adı
          predicates:
            - Path=/engine/**   # istek yolu
            - Path=/iflow-engine/**   # istek yolu
        - id: iflow-identity
          uri: lb://iflow-identity  # Eureka'da kayıtlı olan servis adı
          predicates:
            - Path=/identity/**   # istek yolu
            - Path=/iflow-identity/**   # istek yolu
      default-filters:
        - StripPrefix=1
        - name: GatewaySecurityFilter
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 100
            key-resolver: "#{@clientIdKeyResolver}"      

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: "http://localhost:8081/eureka"
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

server:
  port: 8080

security:
  jwksBaseUrl: http://localhost:8088
  type: default
  enable: true
  restricted: false
  jwt:
    secret: K1zsNyPjyYwP1P/WlYKke8BqzAudLfbyTwYMgMVKCIw=
  default-admin:
    id: fa6ee30d-e476-4435-951f-d43bf84eee05
    email: admin@iflow.com
    roles:
      - ADMIN    
      
