spring:
  application:
    name: iflow-engine
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: engine_user
    password: iknow24
    url: jdbc:postgresql://localhost:5432/iflow_engine
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8088/api/.well-known/jwks.json
          audiences:
            - engine
            - iflow-engine
          issuer-uri: http://localhost:8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: "http://localhost:8081/eureka"
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

iflow:
  timer:
    max-retry-count: 26

camunda:
  bpm:
    job-execution:
      enabled: true
    generic-properties:
      properties:
        user-resource-whitelist-pattern: "^[a-zA-Z0-9_-]+$"
    database:
      schema-update: true
    enabled: true
    process-engine-name: default
    auto-deployment-enabled: true
server:
  port: 3031
  servlet:
    context-path: /api
grpc:
  server:
    port: 0
    
logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
