spring:
  datasource:
    username: engine_user
    password: iknow24
    url: jdbc:postgresql://localhost:5432/iflow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8088/api/.well-known/jwks.json
          audiences: "iflow"
          issuer-uri: http://localhost:8088
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: iflow
  deploy-bucket: iflow-deploy
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8081/eureka"
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true


server:
  port: 0
  servlet:
    context-path: /api

iflow:
  client:
    secret: iflow-secret


