spring:
  datasource:
    username: engine_user
    password: iknow24
    url: jdbc:postgresql://172.16.11.53:5432/iflow_simulator
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://172.16.11.52:8081/eureka"
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true


server:
  port: 0
  servlet:
    context-path: /api
