spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: iflow-rest-api
          uri: lb://iflow  # Eureka'da kayıtlı olan servis adı
          predicates:
            - Path=/iflow/**   # istek yolu
          filters:
            - StripPrefix=1
        - id: iflow-engine
          uri: lb://engine  # Eureka'da kayıtlı olan servis adı
          predicates:
            - Path=/engine/**   # istek yolu
          filters:
            - StripPrefix=1
        - id: iflow-identity
          uri: lb://iflow-identity  # Eureka'da kayıtlı olan servis adı
          predicates:
            - Path=/identity/**   # istek yolu
          filters:
            - StripPrefix=1
        - id: iflow-simulator
          uri: lb://iflow-simulator  # Eureka'da kayıtlı olan servis adı
          predicates:
            - Path=/simulator/**   # istek yolu
          filters:
            - StripPrefix=1
      default-filters:
        - name: GatewaySecurityFilter

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: "http://localhost:8081/eureka"
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

server:
  port: 8080

security:
  enable: true
  default-admin:
    id: fa372e8b-1e65-4c84-8558-fbd217319d41
    email: admin@iflow.com
    roles:
      - ADMIN
