spring:
  application:
    name: rune
  datasource:
    username: engine_user
    password: iknow24
    url: jdbc:postgresql://192.168.1.13:5432/iflow_jwks
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    enabled: false
    refresh:
      enable: false

server:
  port: 8088

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwks:
  issuer: "http://localhost:8088"
  rotation:
    cron: "0 0 3 * * MON" # Every Monday 03:00 server time
    keep-previous-days: 2 # Keep retired keys for 2 days for validation
  token-ttl-minute: 60
  service-clients:
      - client-id: iflow
        secret: "iflow-secret"
        name: "IFlow"
        description: "IFlow main REST API"
      - client-id: primum
        secret: "engine-secret"
        name: "IFlow Primum"
        description: "IFlow BPMN engine"
      - client-id: aegis
        secret: "aegis-secret"
        name: "IFlow Aegis"
        description: "IFlow identity & access management"
      - client-id: oracle
        secret: "simulator-secret"
        name: "IFlow Oracle"
        description: "IFlow process simulation"


